[package]
name = "idkncc/better-react-components"
version = "3.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = [ "src", "default.project.json", "README.md" ]

[dependencies]
react = "jsdotlua/react@~17.2"
react-roblox = "jsdotlua/react-roblox@~17.2"

[dev-dependencies]
ui-labs = "pepeeltoro41/ui-labs@2.3.8"
